### PR TITLE
Experimental data setup with essentiality [WIP]

### LINKED ISSUE #39: Develop species specific data import formats for biolog data and gene essentiality data

### LINKED ISSUE #77: Compare with gene essentiality data
Are knock-outs giving the same results? Is essentiality predicted correctly?

### PR DESCRIPTION
**Pull request by ChristianLieven**
fix #77 and fix #39 

This pull-request lays the foundation to handling experimental data in memote and implements a first example of using this data in the form of comparative gene essentiality tests.

Here is an example:
For a simple gene essentiality screen, the user has created single-knockout strains of E. coli. He has then characterised their ability to grow on minimal medium on glucose. To test the metabolic model he may now provide a tab-delimited file with the columns 'Gene ID' and 'Growth Rate' in the root of the memote directory. When memote tests are then executed, this CSV file is parsed and the experiment is reconstructed in-silico using the default model state. The result will be a table showing the experimental data vs the model's predictions. The model will pass the test if the amount of true positives is equal to the total amount of data points.

Optionally, the user may provide a config.yml file which further specifies the conditions used in his experiments. Currently he may only determine a simple objective function. However, we plan to extend experimental data IO and configuration, as outlined [here](https://github.com/biosustain/memote/wiki/Supported-Experimental-Data).

### CODE REVIEW

**Comment by ChristianLieven** [comment]
Didn't see that we had #39 when I opened the PR. I think this PR resolves the issue too.

**Comment by Midnighter** [comment]
Please add the Sphinx numpydoc extension to the `conf.py` since all our docstrings are in that format. And while you're at it maybe choose another Sphinx theme. The default one is getting quite old.

**Comment by Midnighter** [comment]
Resolve #110, #74, #72, #71, and #68.

**Comment by ChristianLieven** [comment]
Could the reason why this is failing be:

[>[...] having collected enough commits since the last tag, that travis no longer includes a tag in the recent history](https://github.com/pytest-dev/pytest/issues/2779)

**Comment by Midnighter** [comment]
This PR is still in progress and far from done :disappointed: I'll mark it as such.

**Comment by ChristianLieven** [comment]
I'm going to collect a few relevant papers here:

https://bmcsystbiol.biomedcentral.com/track/pdf/10.1186/1752-0509-4-178?site=bmcsystbiol.biomedcentral.com

**Comment by Midnighter** [comment]
I'm closing this one in favor of #400 but there is still a lot of validation that needs to be done.

**Pull request closed without merging**
