### PR TITLE
fix: bring memote back up to speed with recent cobra release

### LINKED ISSUE #445: Unpin Cobrapy Dependency and fix all associated errors
#### Problem description
Pinned the cobrapy version to  0.12.0 since the new release (0.12.1/ 0.13.0) cause breaking changes, which would require a larger refactor.

After this sprint, this should be fixed thoroughly!

### PR DESCRIPTION
**Pull request by ChristianLieven**
* [x] fix #445 
* [x] Unpinned the Cobrapy dependency and updated memote's uses of `model.exchanges` to `model.boundary` where appropriate.
* [x] add an entry to the [next release](../HISTORY.rst)

### CODE REVIEW

**Comment by ChristianLieven** [comment]
@midnighter Do you think we could disable the tests relating to our `syntax.py` helper module? The functions there are deprecated and not used in any of the core tests.

**Comment by Midnighter** [comment]
Absolutely, I will make a quick PR to remove them. Didn't even realize that we're still lugging them around.

**Comment by Midnighter** [comment]
Done, so try again after rebasing.

**Comment by ChristianLieven** [comment]
This should not fail anymore once this fix to cobrapy is merged: https://github.com/opencobra/cobrapy/pull/733

**Pull request merged**
